from array import array
from typing import Any, Iterable, Protocol, TypeVar
import usb._objfinalizer as _objfinalizer
from ._typing import (
    ConfigurationDescriptorProtocol,
    DeviceDescriptorProtocol,
    EndpointDescriptorProtocol,
    InterfaceDescriptorProtocol,
)

from . import libusb0, libusb1, openusb

__all__ = ["IBackend", "libusb0", "libusb1", "openusb"]

T_DEV = TypeVar("T_DEV")
T_DEVH = TypeVar("T_DEVH")

class BackendProtocol(Protocol[T_DEV, T_DEVH]):
    def enumerate_devices(self) -> Iterable[T_DEV]: ...
    def get_parent(self, dev: T_DEV) -> T_DEV | None: ...
    def get_device_descriptor(self, dev: T_DEV) -> DeviceDescriptorProtocol: ...
    def get_configuration_descriptor(
        self, dev: T_DEV, config: int
    ) -> ConfigurationDescriptorProtocol: ...
    def get_interface_descriptor(
        self, dev: T_DEV, intf: int, alt: int, config: int
    ) -> InterfaceDescriptorProtocol: ...
    def get_endpoint_descriptor(
        self, dev: T_DEV, ep: int, intf: int, alt: int, config: int
    ) -> EndpointDescriptorProtocol: ...
    def open_device(self, dev: T_DEV) -> T_DEVH: ...
    def close_device(self, dev_handle: T_DEVH) -> None: ...
    def set_configuration(self, dev_handle: T_DEVH, config_value: int) -> None: ...
    def get_configuration(self, dev_handle: T_DEVH) -> int: ...
    def set_interface_altsetting(
        self, dev_handle: T_DEVH, intf: int, altsetting: int
    ) -> None: ...
    def claim_interface(self, dev_handle: T_DEVH, intf: int) -> None: ...
    def release_interface(self, dev_handle: T_DEVH, intf: int) -> None: ...
    def bulk_write(
        self, dev_handle: T_DEVH, ep: int, intf: int, data: array[int], timeout: int
    ) -> int: ...
    def bulk_read(
        self, dev_handle: T_DEVH, ep: int, intf: int, buff: array[int], timeout: int
    ) -> int: ...
    def intr_write(
        self, dev_handle: T_DEVH, ep: int, intf: int, data: array[int], timeout: int
    ) -> int: ...
    def intr_read(
        self, dev_handle: T_DEVH, ep: int, intf: int, buff: array[int], timeout: int
    ) -> int: ...
    def iso_write(
        self, dev_handle: T_DEVH, ep: int, intf: int, data: array[int], timeout: int
    ) -> int: ...
    def iso_read(
        self, dev_handle: T_DEVH, ep: int, intf: int, buff: array[int], timeout: int
    ) -> int: ...
    def ctrl_transfer(
        self,
        dev_handle: T_DEVH,
        bmRequestType: int,
        bRequest: int,
        wValue: int,
        wIndex: int,
        data: array[int],
        timeout: int,
    ) -> int: ...
    def clear_halt(self, dev_handle: T_DEVH, ep: int) -> None: ...
    def reset_device(self, dev_handle: T_DEVH) -> None: ...
    def is_kernel_driver_active(self, dev_handle: T_DEVH, intf: int) -> bool: ...
    def detach_kernel_driver(self, dev_handle: T_DEVH, intf: int) -> None: ...
    def attach_kernel_driver(self, dev_handle: T_DEVH, intf: int) -> None: ...

# Implementation of BackendProtocol[Any, Any]
# Do not inherit BackendProtocol here, or both Pyright and mypy will fail to detect
# broken signature declarations in classes that inherit from IBackend.
# Ideally we want this to be a Generic, but this will not work at run time due to
# how inheritance works.
class IBackend(_objfinalizer.AutoFinalizedObject):
    def enumerate_devices(self) -> Iterable[Any]: ...
    def get_parent(self, dev: Any) -> Any | None: ...
    def get_device_descriptor(self, dev: Any) -> DeviceDescriptorProtocol: ...
    def get_configuration_descriptor(
        self, dev: Any, config: int
    ) -> ConfigurationDescriptorProtocol: ...
    def get_interface_descriptor(
        self, dev: Any, intf: int, alt: int, config: int
    ) -> InterfaceDescriptorProtocol: ...
    def get_endpoint_descriptor(
        self, dev: Any, ep: int, intf: int, alt: int, config: int
    ) -> EndpointDescriptorProtocol: ...
    def open_device(self, dev: Any) -> Any: ...
    def close_device(self, dev_handle: Any) -> None: ...
    def set_configuration(self, dev_handle: Any, config_value: int) -> None: ...
    def get_configuration(self, dev_handle: Any) -> int: ...
    def set_interface_altsetting(
        self, dev_handle: Any, intf: int, altsetting: int
    ) -> None: ...
    def claim_interface(self, dev_handle: Any, intf: int) -> None: ...
    def release_interface(self, dev_handle: Any, intf: int) -> None: ...
    def bulk_write(
        self, dev_handle: Any, ep: int, intf: int, data: array[int], timeout: int
    ) -> int: ...
    def bulk_read(
        self, dev_handle: Any, ep: int, intf: int, buff: array[int], timeout: int
    ) -> int: ...
    def intr_write(
        self, dev_handle: Any, ep: int, intf: int, data: array[int], timeout: int
    ) -> int: ...
    def intr_read(
        self, dev_handle: Any, ep: int, intf: int, buff: array[int], timeout: int
    ) -> int: ...
    def iso_write(
        self, dev_handle: Any, ep: int, intf: int, data: array[int], timeout: int
    ) -> int: ...
    def iso_read(
        self, dev_handle: Any, ep: int, intf: int, buff: array[int], timeout: int
    ) -> int: ...
    def ctrl_transfer(
        self,
        dev_handle: Any,
        bmRequestType: int,
        bRequest: int,
        wValue: int,
        wIndex: int,
        data: array[int],
        timeout: int,
    ) -> int: ...
    def clear_halt(self, dev_handle: Any, ep: int) -> None: ...
    def reset_device(self, dev_handle: Any) -> None: ...
    def is_kernel_driver_active(self, dev_handle: Any, intf: int) -> bool: ...
    def detach_kernel_driver(self, dev_handle: Any, intf: int) -> None: ...
    def attach_kernel_driver(self, dev_handle: Any, intf: int) -> None: ...
